충남대 Android_김재민 5주차 과제 STEP 1
kakao-tech-campus-2nd-step2/android-map-refactoring pull request #23
Opened 2024-07-23 10:56 UTC by Kjamm

## 코드 작성하면서 어려웠던 점
- 의존성 주입에 대한 개념이 완벽하게 이해되지 않아, 코드가 제대로 작성되었는지 모르겠습니다.
- Room으로 데이터베이스를 바꿀 때, 조금만 수정하면 될 줄 알았지만 생각보다 수정해야 될 부분이 많아 힘들었습니다.
- REST API 401 오류가 갑자기 떠 오류를 해결하는 과정 중 gpt, 인터넷 검색 등 자료를 찾아봤지만 생각보다 명확한 답이 없이 해결하기 힘들었습니다.

## 중점적으로 리뷰해주셨으면 하는 부분
- 이번 미션 목표인 의존성 주입,  Room으로 db 변경이 제대로 이루어졌는지 리뷰해주셨으면 좋겠습니다.

## 결과화면
- 이전과 동일

https://github.com/user-attachments/assets/3a66e2a8-a0ba-400d-b995-cbfb38ee2fb7

2024-07-24 14:05 UTC, InyoungAum requested changes
수고하셨습니다!

2024-07-24 14:05 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/di/AppModule.kt
> +        return Repository(sharedPreferences, keywordDao, kakaoLocalApiService)
이렇게 Repo자체를 생성해도 가능하지만 이렇게 되면 Repo에서 굳이 inject를 해줄 필요가 없어집니다. 
또한 완벽한 클린아키텍쳐 기반의 멀티모듈을 적용했을때 Repo의 구현체를 알고있어야하는 문제가 생기게 되는데요 

https://hungseong.tistory.com/29

위의 블로그를 참고해서 Repo interface, RepoImpl을 생성하고  bind하는 방법으로 한번 변경해보시기 바랍니다

2024-07-24 14:05 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/di/AppModule.kt
> +            "SearchData.db"
이러한 고정된 String들도 주입하는 방법으로 쓰면 유용한데요 
하나이상의 같은 형태를 주입하기 위해서는 @qualifier 어노테이션을 사용해야합니다. 

https://seosh817.tistory.com/76

위 블로그를 참고하여 String 상수들도 주입해보시기 바랍니다

2024-07-24 14:05 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/di/AppModule.kt
> +object AppModule {
지금은 플젝이 작아서 AppModule 하나에 모두 작업을 해주셨는데요 
커질수록 모듈을 분리해서 관리하게 됩니다. 네트워크와 repo등으로 모듈 파일을 분리해보시기 바랍니다!

2024-07-24 14:05 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/di/AppModule.kt
> +        return Room.databaseBuilder(
작성해두신 getDatabase를 사용하거나 어차피 주입하는 것 이므로 getDatabase 함수는 제거되어도 될 것 같네요

2024-07-24 14:05 UTC, InyoungAum commented on app/src/main/java/campus/tech/kakao/map/data/AppDatabase.kt
> +        private fun buildDatabase(context: Context) =
아래 모듈코드와 중복이네요

2024-07-24 14:30 UTC, InyoungAum commented
401오류는 인증관련 된 오류인데요 네트워크 모듈을 주입하는 것으로 바꾸면서 API_KEY등이 정상적으로 들어갔나 혹은 만료된 것은 없나 체크해보시기 바랍니다

2024-07-24 14:35 UTC, Kjamm commented on app/src/main/java/campus/tech/kakao/map/di/AppModule.kt
> +        return Repository(sharedPreferences, keywordDao, kakaoLocalApiService)
넵 반영해보겠습니다!

2024-07-24 14:36 UTC, Kjamm commented on app/src/main/java/campus/tech/kakao/map/di/AppModule.kt
> +            "SearchData.db"
넵 좋은 자료들 감사합니다!

2024-07-24 14:42 UTC, Kjamm commented
> 401오류는 인증관련 된 오류인데요 네트워크 모듈을 주입하는 것으로 바꾸면서 API_KEY등이 정상적으로 들어갔나 혹은 만료된 것은 없나 체크해보시기 바랍니다

자세한 원인은 모르겠으나, 카카오 디벨로퍼스 Q&A, 인터넷 등을 참고하여 앱 키 재발급 -> rebuild project 하니 해결 되었습니다. 감사합니다!

2024-07-26 16:51 UTC, InyoungAum commented
수고하셨습니다!

2024-07-26 16:51 UTC, merged