Step1
kakao-tech-campus-2nd-step2/android-map-refactoring pull request #38
Opened 2024-07-24 09:38 UTC by settle54

2024-07-27 02:49 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/data/dao/PlaceDao.kt
> +import kotlinx.coroutines.flow.Flow
소소한 부분이지만 커밋 전에 참조가 끊긴 Import문을 정리해주세요. 파일을 깔끔하게 유지하기 위함입니다. 아래 2가지 중 편하신 방법을 택하시면 됩니다.

1. 단축키 이용하기
> Optimize imports: Control+Alt+O

2. 설정에서 자동으로 정리해주는 옵션 이용하기
![image](https://github.com/user-attachments/assets/b14af557-bd36-41a3-acc4-88a731c15b3f)

2024-07-27 07:03 UTC, kold-brewed requested changes
리팩터링을 거치면서 패키지 구조가 이전주차보다 패턴에 맞게 세분화되었네요 👍 좀 더 시도해보셨으면 하는 부분이나 수정이 필요한 부분들에 대해 코멘트 남겨두었습니다. 고생하셨습니다~

2024-07-27 07:03 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/data/dao/PlaceDao.kt
> +import kotlinx.coroutines.flow.Flow
소소한 부분이지만 커밋 전에 참조가 끊긴 Import문을 정리해주세요. 파일을 깔끔하게 유지하기 위함입니다. 아래 2가지 중 편하신 방법을 택하시면 됩니다.

**1. 단축키 이용하기**
> Optimize imports: Control+Alt+O  

**2. 설정에서 자동으로 정리해주는 옵션 이용하기**
![image](https://github.com/user-attachments/assets/7d8ae459-a161-4df5-821b-2ec0efb3c381)

2024-07-27 07:03 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/data/network/api/RetrofitService.kt
> +    ): Call<SearchResponse>
2단계에서는 네트워크 비동기처리에도 코루틴을 활용해보시면 좋겠습니다.
```suggestion
    suspend fun requestPlaces(
        @Header("Authorization") auth: String = KEY,
        @Query("query") query: String
    ): SearchResponse
```
수정하면서 함께 생각해볼만한 내용입니다.
- 가독성 측면에서 두가지 방식의 비교
- suspend 키워드를 달았을 때 네트워크 콜이 수행되는 쓰레드
- 반환형 타입(Result<SearchResponse>, SearchResponse)에 따른 예외처리 방식

더 깊게는 suspend 키워드를 달았을 때 Retrofit 내부에서는 어떻게 enqueue가 수행되는 것인지 까지도 살펴보시면 좋겠습니다.

2024-07-27 07:03 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/data/network/dto/Document.kt
> +    val y: String
이번주차 과제의 범위는 아니지만,
안드로이드에서 사용하는 직렬화 라이브러리는 gson 외에 **kotlin-serialization**도 있습니다. 

시간 되실 때 gson에서 kotlin-serialization으로 변경해보면서 아래 키워드들을 중심으로 둘의 장단점과 주의할 점등을 학습해보시면 좋겠습니다.
- null 응답값 처리
- default value

더 나아간다면 DataStore에 최근 검색어를 저장하고 읽을 때 쓴 gson에도 적용해볼 수 있겠네요.

🔗 https://kotlinlang.org/docs/serialization.html#serialize-and-deserialize-json

2024-07-27 07:03 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/data/network/dto/SearchResponse.kt
> +    val meta: Meta
지금은 모든 네트워크 응답 모델 필드들을 non-null로 정의하셨네요.
API 명세를 보았을 때 해당 필드가 optional로 되어있다면 어떻게 정의해야 할지도 생각해보시면 좋을 것 같아요.

2024-07-27 07:03 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/data/model/Place.kt
> +@Parcelize
여기 Deprecated된 패키지의 어노테이션이 참조된 것 같네요 👀
> Parcelize annotations from package 'kotlinx.android.parcel' are deprecated. Change package to 'kotlinx.parcelize'

2024-07-27 07:03 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/data/database/PlacesDBHelper.kt
> +class PlacesDBHelper @Inject constructor(@ApplicationContext context: Context) :
과제는 데이터베이스를 Room으로 변경하는 것이었습니다. 기존 SQliteOpenHelper를 이용하는 코드를 남겨두신채 제출하시면 참조되지 않고 있는 함수들이 파일에 섞이게 되어 원활한 코드리뷰가 어렵습니다.
SQLiteOpenHelper 학습을 위해 코드를 남겨두고 싶으신 경우에는 개인 리포에서 별도 브랜치를 생성해 관리해주시고, 과제 제출용 브랜치에서는 Room 관련 코드만 남기고 기존에 작성하셨던 PlacesDBHelper 및 참조하지 않게된 함수는 모두 제거해주세요.

2024-07-27 07:03 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/data/database/PlacesRoomDB.kt
> +    }
아래 AppModule에 정의하신 부분의 의미를 다시 한번 생각해봐주시고, 필요하다면 PlacesRoomDB 클래스를 수정해주세요.
```kotlin
@Provides
@Singleton
fun providePlacesDatabase (@ApplicationContext context: Context): PlacesRoomDB {
    return PlacesRoomDB.getDatabase(context)
}
```

2024-07-27 07:03 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/ui/activity/SearchActivity.kt
> +        }
이 때의 Intent는 데이터를 담는 역할만을 수행하기 때문에 아래와 같이 파라미터가 없는 생성자를 호출해 Intent를 생성하는 것이 좋습니다.
```suggestion
        val intent = Intent().apply {
            putExtra("place", place)
        }
```

2024-07-27 07:03 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/ui/activity/SearchActivity.kt
> +            binding.searchHistory.isVisible = searchHistoryData.isNotEmpty()
submitList()함수는 비동기로 동작하기 때문에 91번줄부터의 순서는 보장되지 않습니다. (목록화면 갱신 전에 이미 아래줄이 실행 될 수있습니다.)

만약 submitList를 호출한 뒤, 화면에 다 그려지고 나서 어떤 일을 수행하고 싶은 경우에는 아래 함수를 이용해 commitCallback을 작성해야 한다는 점도 알아두시면 좋겠습니다.
`public void submitList(@Nullable List<T> list, @Nullable final Runnable commitCallback)`

2024-07-27 07:03 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/ui/activity/SearchActivity.kt
> +            lifecycleScope.launch {
여기 launch를 선언하신 이유가 궁금합니다 👀 insertSearch와 savePos 함수 내부를 보니 이미 각각 코루틴을 생성해 실행되고 있는 것 같아보여서요.

2024-07-27 07:03 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/data/repository/MapRepository.kt
> +        })
Retrofit도 Hilt를 이용해 Service 의존성을 주입받도록 수정해보시면 좋을 것 같아요!

2024-07-27 07:05 UTC, kold-brewed commented
@settle54 충돌 수정하시는 과정에서 패키지 이동 전에 몇몇 클래스들이 추가되면서 프로젝트 내 중복으로 존재하는 상황이예요. 개인리포에서 step1 브랜치로 빌드하면 빌드오류가 발생할겁니다. 수정해주신 다음에 1단계 머지 진행할게요!

2024-07-27 07:08 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/data/repository/DataStoreManager.kt
> +        }
catch문에서 딱히 처리하고 싶은 내용이 없다면 runCatching {} 을 이용해보는 방법도 있습니다.
```suggestion
        kotlin.runCatching {
            Log.d("datastore", "getLastPos: ${Thread.currentThread().name}")
            val preferences = dataStore.data.first()
            val json = preferences[LAST_POSITION_KEY] ?: return null
            return GsonBuilder().create().fromJson(json, LatLng::class.java)
        }
```

2024-07-27 07:10 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/data/repository/DataStoreManager.kt
> +class DataStoreManager @Inject constructor(private val dataStore: DataStore<Preferences>) {
DataStore도 적절히 잘 작성해주셨네요 👏

2024-07-27 08:30 UTC, merged

2024-07-27 09:13 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/ui/viewModel/MapViewModel.kt
> +            repository.insertRoomInitialData()
repository.insertRoomInitialData() 내부에서 호출하는 localRoom.placeDao().insertAll() suspend 키워드를 달고 있습니다. 라이브러리 내부에서는 suspend 키워드를 붙였을 때 어떤 쓰레드에서 쿼리를 수행하는지 알아보시면 좋을 것 같아요.

2024-07-30 05:47 UTC, settle54 commented on app/src/main/java/campus/tech/kakao/map/ui/activity/SearchActivity.kt
> +            lifecycleScope.launch {
코루틴을 여기저기 적용해보다가 차마 지우지 못한 것 같아요 ㅎㅎ 해당 부분 삭제했습니다!

2024-07-30 05:49 UTC, settle54 commented on app/src/main/java/campus/tech/kakao/map/ui/viewModel/MapViewModel.kt
> +            repository.insertRoomInitialData()
뷰모델에서 할당한 디스패처 스레드를 사용하고 있었습니다!

2024-07-30 06:03 UTC, settle54 commented on app/src/main/java/campus/tech/kakao/map/data/database/PlacesRoomDB.kt
> +    }
ApplicationContext를 인자로 받는데 `context.applicationContext`를 사용했기 때문인가요...?
이 부분을 실수한 것 같아 수정했는데, 확인 차 여쭤봅니다....ㅠㅠ

2024-07-31 14:59 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/data/database/PlacesRoomDB.kt
> +    }
아뇨~ 짚어드리고 싶었던 부분은 `@Singleton`어노테이션의 의미와 PlacesRoomDB에 선언된 Instance였어요!

2024-07-31 15:08 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/ui/activity/SearchActivity.kt
> +            lifecycleScope.launch {
@settle54 음 lifecycleScope를 라이브러리 내부로 따라 들어가보면 Main Thread에서 코루틴을 실행하고 있어요.
`SupervisorJob() + Dispatchers.Main.immediate`
그리고 viewModel.insert 함수 내부에서는 IO 쓰레드로 코루틴을 또다시 생성하고 있구요. 
'launch를 하면 무조건 다른 스레드에서 작동' -> 이건 조금 혼동의 여지가 있어보이네요. launch에 Dispatchers를 지정해주지 않으면 보통은 launch를 호출한 쓰레드에서 코루틴이 수행될거라서요.

2024-07-31 15:33 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/ui/viewModel/MapViewModel.kt
> +            repository.insertRoomInitialData()
suspend 키워드가 붙은 dao 쿼리는 Room 내부에서 자체적으로 생성한 백그라운드 쓰레드를 이용해 수행되기 때문에 사실 76줄과 같이 IO쓰레드로 명시하지 않아도 된다는 이야기를 드리고 싶었어요..!

2024-08-01 05:57 UTC, settle54 commented on app/src/main/java/campus/tech/kakao/map/data/database/PlacesRoomDB.kt
> +    }
```kotlin
companion object {

        fun getDatabase(context: Context): PlacesRoomDB {
            return Room.databaseBuilder(
                    context,
                    PlacesRoomDB::class.java, DATABASE_NAME
                ).build()
        }
    }
``` 

`@Singleton` 자체가 고유성을 증명하기 때문에 `instance`를 이용한 싱글톤 패턴이 필요없다는 말씀이신가요...?! 🤔

2024-08-01 13:29 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/data/database/PlacesRoomDB.kt
> +    }
맞아요. `@Singleton` 어노테이션을 선언하면 Hilt에게 싱글톤으로 관리해달라고 하는 것이니까요. 말씀하신 혹시 모를 상황이라고 한다면.. 한 프로젝트 내에 Hilt를 사용하는 모듈과 그렇지 않은 모듈이 동시에 존재하면서 두 모듈 다 PlacesRoomDB를 필요로 하는 경우가 있을 것 같아요. 지금은 그렇지 않기도 하고, 객체화하는 방식을 하나로 통일해두는 것이 좋지 않을까 싶네요. 👀