강원대 Android_권새일 5주차 과제 Step1
kakao-tech-campus-2nd-step2/android-map-refactoring pull request #46
Opened 2024-07-25 05:40 UTC by todlf

**어려웠던 점**
- Hilt를 처음 써봐서 어려웠습니다.
- 코드를 리팩토링 하는 과정에서 잘 적용하고 있는지 생각이 많아졌습니다.
- MVVM도 조금은 적용해봤는데, 2단계에서 DataBinding 쓰고 분리하고 정리해야 할 것 같습니다.

**중점적으로 리뷰해주셨으면 하는 부분**
- Room을 맞게 썼는지 궁금합니다.
- Hilt를 잘 적용했는지, 추가적으로 의존성 주입할 부분이 있는지 궁금합니다.
- MVVM 패턴으로 패키지 분리가 알맞게 되었는지 궁금합니다.

2024-07-27 13:31 UTC, kold-brewed requested changes
Room과 Hilt를 잘 작성해주셨어요. 전보다 훨씬 코드가 간결해졌네요 👍 고생하셨습니다!!

2024-07-27 13:31 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/data/SearchRepository.kt
>                              )
이번주차 과제 목표와는 조금 다른 부분이지만, for loop 안에서 insert를 수행하고 있네요. 
성능적인 측면에서 데이터 1개에 대한 insert를 1000번 반복하는 것과 1000개의 데이터를 한번의 insert문으로 수행하는 상황에 대해서도 한번 고민해주시면 좋겠습니다. 코틀린 measuretimeXX 함수를 이용해 소요시간이 얼마나 차이나는지 직접 테스트해보시는 것도 좋겠네요.

2024-07-27 13:31 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/domain/model/SavedSearch.kt
> +)
테이블 구성이 아주 단순한 편이네요. 로컬 저장소는 SharedPreferences와 DB 2가지 선택지가 있을텐데 DB를 선택하신 이유가 궁금합니다 👀

2024-07-27 13:31 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/presentation/view/SearchActivity.kt
> +    private fun liveDataObserver() {
> The name of a class is usually a noun or a noun phrase explaining what the class is: List, PersonReader. The name of a method is usually a verb or a verb phrase saying what the method does: close, readPersons.

함수명은 동사로 시작하도록 작성해주시면 좋겠습니다.

🔗  https://kotlinlang.org/docs/coding-conventions.html#choose-good-names

2024-07-27 13:31 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/presentation/view/SearchActivity.kt
>          savedWordClick()
여기도 마찬가지로 동사로 시작하도록 함수 네이밍 컨벤션을 지켜서 작성해주시면 좋겠습니다.

2024-07-27 13:31 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/presentation/view/SearchActivity.kt
> +        searchViewModel.fetchData()
loadSavedWords와 같이 fetchData도 어떤 정보를 불러오기 위함인지가 이름에 좀 더 드러나면 좋을 것 같아요.

2024-07-27 13:31 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/presentation/viewmodel/KakaoMapViewModel.kt
> +) : ViewModel() {
context는 메모리릭의 위험성 때문에 안드로이드 ViewModel(디자인패턴의 ViewModel 아님)로 직접 주입하는 것을 권장하지 않습니다. applicationContext 역시도 권장하고 싶은 방법은 아니예요. Hilt를 이용해 SharedPreference가 ViewModel로 주입되도록 해보시면 좋겠습니다.

2024-07-27 13:31 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/presentation/viewmodel/KakaoMapViewModel.kt
> +            sharedPref.getString("yCoordinate", "37.402005")?.toDoubleOrNull() ?: 37.402005
SharedPreferences에서 사용되는 key값은 읽고쓸 때 항상 같아야 하기 때문에 const로 선언해주시는 것이 좋습니다.

`private const val KEY_X_COORDINATE` = "xCoordinate"

2024-07-27 13:43 UTC, kold-brewed commented
> MVVM 패턴으로 패키지 분리가 알맞게 되었는지 궁금합니다.

domain > model에 담으신 3개의 클래스는 다시 한번 패키지 위치를 생각해보셨으면 해요.
도메인은 MVVM이라기보다는 안드로이드에서 제안하는 클린 아키텍쳐 개념에 포함되어 있는데, 지금정도 크기의 프로젝트에서는 오버스펙이라는 생각을 합니다. 또한, 도메인에서 이야기하는 model은 지금 담아두신 KakaoData, SavedSearch, SearchData와는 조금 다른 개념이예요.

Retrofit, DataBase 모델과 관련해서 DTO, Entity 키워드로 조금 더 학습해보시면 좋겠습니다.

2024-07-27 13:43 UTC, merged

2024-07-27 14:03 UTC, kold-brewed commented on app/src/main/java/campus/tech/kakao/map/data/SearchRepository.kt
> +) {
이제는 RetrofitService 객체도 Hilt를 이용해 주입받아오도록 수정해보면 좋을 것 같아요.
```kotlin
val retrofitService = Retrofit.Builder()
                .baseUrl("https://dapi.kakao.com/")
                .addConverterFactory(GsonConverterFactory.create())
                .build()
                .create(RetrofitService::class.java)
```

2024-07-29 00:57 UTC, todlf commented on app/src/main/java/campus/tech/kakao/map/domain/model/SavedSearch.kt
> +)
전에 SQLite로 저장하라는 요구사항만 충족하려고 하다보니 생각을 못했네요...!
생각해보니, 저장된 검색어가 많아질수록 DB가 관리하기 좋고, 저장된 검색어를 카테고리 별로 분류하거나 그런 기능을 추가하기 좋다고 생각합니다